### PR TITLE
Fix multiline string escaping

### LINKED ISSUE #53: CoffeeScript compilation of `"""` causes incorrect escaping
This is probably an issue with our decaf fork, but putting it here for posterity. The following CoffeeScript:

```coffee
FIXTURE = """
  <div id="outer" style="height: #{CONTAINER_HEIGHT}px; overflow: scroll">
    <div id="inner" style="height: #{CONTENT_HEIGHT}px"></div>
  </div>
"""
```

Gets compiled to this through `esify`:

```js
const FIXTURE = (`<div id=\\"outer\\" style=\\"height: ${CONTAINER_HEIGHT}px; overflow: scroll\\">\\n  <div id=\\"inner\\" style=\\"height: ${CONTENT_HEIGHT}px\\"></div>\\n</div>`);
```

### PR DESCRIPTION
**Pull request by lemonmade**
Fixes https://github.com/Shopify/javascript/issues/53. I have no idea what mangled logic creates these strings, but the escaping is super messed up and this seems to fix it.

cc/ @GoodForOneFare

### CODE REVIEW

**Comment by GoodForOneFare** [comment]
`escapeQuotes` in `assets/javascripts/admin/lib/string.coffee` is still busted, but not any worse than it already was.  Everything else looks fine, and this can 🚢 if another issue is raised for `escapeQuotes`.

**Comment by GoodForOneFare** [comment]
`design_mode_next/live_colors.coffee` has a regex with too many backslashes.  The multiline fix gets it closer to being correct.

| Transform | Result |
| --- | --- |
| js2.coffee | `/\/\*\!setting\.["\s]*foo["\s]*\{\*\/([^\}]*)\/\*\}\*\//g` |
| Decaf with multiline fix | `/\/\\*\\!setting\\.["\\s]*foo["\\s]*\\{\\*\\/([^\\}]*)\\/\\*\\}\\*\\//g` |
| Decaf without multiline fix | `/\/\\*\\!setting\\.[\"\\s]*foo[\"\\s]*\\{\\*\\/([^\\}]*)\\/\\*\\}\\*\\//g` |

**Comment by lemonmade** [comment]
@GoodForOneFare can you check again? I think I might have a better fix that addresses both cases you mentioned. We should still probably put a warning in `esify` to check any string/ regex that contains complex escape sequences.

**Comment by GoodForOneFare** [comment]
The good news: this fixes a ton of problems that I missed in the original :tophat:.

The less good news:

`admin/modules/index_search.coffee` - now throws a decaf transform exception

`admin/lib/regexp` - backslashes are removed from special regexp chars

| Transform | Code |
| --- | --- |
| Coffee | `SPECIAL_REGEXP_CHARS = /[|\\{}()[\]^$+*?.]/g` |
| JS2coffee | `SPECIAL_REGEXP_CHARS = /[|\\{}()[\]^$+*?.]/g;` |
| Initial fix | `SPECIAL_REGEXP_CHARS = /[|\\{}()[\]^$+*?.]/g;` |
| Latest fix | `SPECIAL_REGEXP_CHARS = /[|\{}()[\]^$+*?.]/g;` |

`admin/modules/i18n/language-editor` - inserts a newline into the regexp (not sure how decaf doesn't cough up an exception on this)

| Transform | Code |
| --- | --- |
| Coffee | `"#{_.escape(text).replace(/\n/g, '<br>')}<br>"` |
| JS2coffee | `(_.escape(text).replace(/\n/g, '<br>')) + "<br>";` |
| Initial fix | `((_.escape(text).replace(/\n/g, '<br>')) + '<br>');` |
| Latest fix | line-break-in-code |

`unit/lib/string-test` - missing backslashes

| Transform | Code |
| --- | --- |
| Coffee | `assert.equal '\\"who\\\'s that?\\"'` |
| JS2coffee | `assert.equal('\\"who\\\'s that?\\"'` |
| Initial fix | `assert.equal('\\"who\\\'s that?\\"'` |
| Latest fix | `assert.equal('"who\'s that?"'` |

**Comment by bouk** [comment]
I think I have a better fix for this

**Comment by bouk** [comment]
https://github.com/juliankrispel/decaf/pull/139

**Comment by GoodForOneFare** [comment]
Still coughs up on `index_search.coffee`'s `ESCAPE_REGEXP = /([.*+?^=!:${}()|\[\]\/\\])/g`.

`lib/string.coffee` won't escape single quotes in the same way

Coffee: `return str.replace(/'/g, '\'').replace(/"/g, '\\"');`

JS: `return str.replace(/'/g, '\'').replace(/"/g, '\\"');`

**Comment by lemonmade** [comment]
Let's fix those two manually. I've added a note to `esify` that there are potential issues with string escaping, I think that's a reasonable enough solution.

**Pull request closed without merging**
